# Change these first
owner: dissm-inpe # Your GitHub organization or username, where this repository lives
repo: dsat-upptime # The name of this repository

sites:
  - name: DSAT
    url: https://www.cptec.inpe.br/dsat

status-website:
  baseUrl: /dsat-upptime
  logoUrl: https://raw.githubusercontent.com/dissm-inpe/dsat-upptime/master/assets/dsat-icon.png
  theme: night
  name: DSAT | DISSM/INPE
  introTitle: "**DSAT** is a web-based tool for interactive visualization of GOES-16 data and products received and processed by INPE."
  introMessage: This is a status page which uses **real-time** data from [GitHub repository](https://github.com/dissm-inpe/dsat-upptime).
  navbar:
    - title: Status
      href: /dsat-upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: DSAT
      href: https://www.cptec.inpe.br/dsat

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
